### ISSUE TITLE
Choose a direction by Feb 25

### ISSUE THREAD

**Issue by lujiaying** [lujiaying/Open-World-TaxoKG-CoLearning#1]
New project: document structure enhanced downstream task

- [ ] Multi-document summarization (more direct supervision, improved model)
- [x] Recommendation (graph aggregation + graph matching)
- [x] Multi-hop question answering (graph generation + graph reasoning)
- [x] Knowledge graph completion / Common-sense enhanced learning
