### ISSUE TITLE
Draft V1

### ISSUE THREAD

**Issue by lujiaying** [lujiaying/Open-World-TaxoKG-CoLearning#18]
- [x] Oct 12: ~Introduction~, ~Problem~, ~Dataset Creation~ at Oct 17.
- [x] Oct 13: ~Abstract~, ~Model Design~, ~Experiments~ at Oct 18.
- [ ] Oct 14: Experiements, Related Work, Conclusion. Revise Abstract
